### ISSUE TITLE
Clone Y axis

### ISSUE THREAD

**Issue by Lazarus-Rising** [makerbase-mks/MKS-DLC32#13] opened 2021-10-03 19:58 UTC
Hi, I need to be able to clone the Y axis as I need two stepper drivers for the two motors on the Y axis.
Could you post the source code please so I can achieve this?

**Comment by makerbase-mks** [comment] 2021-10-09 05:11
Duplicate of #10

**Comment by Plottmania** [comment] 2021-11-22 04:30
you can use the adapter from Barton and do not need a code.
Remember that the second axis is cloned and therefore mirror-inverted.

![DLC_Stepper_Out](https://user-images.githubusercontent.com/82659592/142801315-af725b6c-f6cf-4c81-9a9e-1decb2fa51eb.jpg)

**Closed** 2022-05-16 07:28 UTC
